// Verify a cert minted in Python decodes + signature-checks here.
import assert from 'node:assert/strict';
import { verifyCert, decodeCertPayload, parseCertFrame, CertVerificationError } from '../../../dist/network/device-cert.js';

// Generated by Python ``issue_cert(coord_key='C'*32, handle='alice',
//   device_pubkey='D'*32, network_id='netuuid-x', now=1700000000.5)``.
const CERT_HEX = '0000008ba76176016668616e646c6565616c6963656d6465766963655f7075626b6579582044444444444444444444444444444444444444444444444444444444444444446a6e6574776f726b5f6964696e6574757569642d78696973737565645f6174fb41d954fc402000006a657870697265735f6174fb41d95edf802000006c6361706162696c697469657380b8cd824ce4684c507ab3d06a6c4de120ab5d6df11831c903a564a82fbdaa5f4493ee99942a96f3028f94a861dcf589e5e5d75421fba4c14a3535241229bc6008';
const COORD_PUB_HEX = '22fc297792f0b6ffc0bfcfdb7edb0c0aa14e025a365ec0e342e86e3829cb74b6';

const wire = Uint8Array.from(Buffer.from(CERT_HEX, 'hex'));
const coordPub = Uint8Array.from(Buffer.from(COORD_PUB_HEX, 'hex'));

// pin "now" to a moment between issuance (1.7e9) and expiry (issued + 30d).
const NOW = 1700000000.5 + 60; // 1 minute later

// 1. Happy path: signature verifies, fields decode correctly.
const cert = await verifyCert(wire, coordPub, { now: NOW });
assert.equal(cert.handle, 'alice');
assert.equal(Buffer.from(cert.devicePubkey).toString('hex'), '44'.repeat(32));
assert.equal(cert.networkId, 'netuuid-x');
assert.equal(cert.issuedAt, 1700000000.5);
assert.equal(cert.expiresAt, 1700000000.5 + 30 * 24 * 3600);
assert.deepEqual(cert.capabilities, []);

// 2. Network-mismatch rejection.
await assert.rejects(
  () => verifyCert(wire, coordPub, { now: NOW, expectedNetworkId: 'other' }),
  (err) => err instanceof CertVerificationError && /expected/.test(err.message),
);

// 3. Expiry rejection.
await assert.rejects(
  () => verifyCert(wire, coordPub, { now: 1700000000.5 + 30 * 24 * 3600 + 1 }),
  (err) => err instanceof CertVerificationError && /expired/.test(err.message),
);

// 4. Wrong coordinator key — sig verification fails.
const wrongPub = new Uint8Array(32).fill(0xff);
await assert.rejects(
  () => verifyCert(wire, wrongPub, { now: NOW }),
  (err) => err instanceof CertVerificationError && /signature/.test(err.message),
);

// 5. parseCertFrame split + decode the payload directly without verifying.
const { payload, signature } = parseCertFrame(wire);
assert.equal(signature.length, 64);
const sameCert = decodeCertPayload(payload);
assert.equal(sameCert.handle, 'alice');

// 6. Truncated wire.
assert.throws(() => parseCertFrame(wire.subarray(0, 60)), /cert too short/);

console.log('cert.test: ok');
