// Compare TS SRP-6a client output against vectors generated by the
// production Python coordinator path (Srp6aBackend + srptools).
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  makeRegistrationPayload,
  startLogin,
  respondLogin,
  verifyServer,
} from '../../../dist/network/srp-client.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fix = JSON.parse(fs.readFileSync(path.join(__dirname, 'srp.fixture.json'), 'utf-8'));

const fromHex = (h) => Uint8Array.from(Buffer.from(h, 'hex'));
const toHex = (b) => Buffer.from(b).toString('hex');

// 1. registration: same salt + same handle/password → same verifier bytes.
//    We can't easily monkey-patch randomness in TS, so we expose a
//    salt-len argument and call with the pinned salt indirectly: rebuild
//    the registration payload with a custom salt by rewinding through
//    ``generatePasswordHash`` + ``generateVerifier`` directly.
//
//    Easier path: just round-trip the fixture's ``register_payload``
//    through TS-side decoding (the bytes match if and only if the SRP
//    primitives are bug-compatible — i.e., a TS verifier rebuilt from
//    the fixture's salt + handle + password should equal the fixture's
//    verifier bytes).
import { SRPClient } from '@windwalker-io/srp';
const PRIME_3072 =
  'FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74' +
  '020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437' +
  '4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED' +
  'EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF05' +
  '98DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB' +
  '9ED529077096966D670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B' +
  'E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9DE2BCBF695581718' +
  '3995497CEA956AE515D2261898FA051015728E5A8AAAC42DAD33170D04507A33' +
  'A85521ABDF1CBA64ECFB850458DBEF0A8AEA71575D060C7DB3970F85A6E1E4C7' +
  'ABF5AE8CDB0933D71E8C94E04A25619DCEE3D2261AD2EE6BF12FFA06D98A0864' +
  'D87602733EC86A64521F2B18177B200CBBE117577A615D6C770988C0BAD946E2' +
  '08E24FA074E5AB3143DB5BFCE0FD108E4B82D120A93AD2CAFFFFFFFFFFFFFFFF';
const c = SRPClient.create(PRIME_3072, '5', '081f4874fa543a371b49a670402fda59ecfab53a1b850fc42e1c357cc846111e');
c.setHasher('sha256').setLength(32);
const saltBig = BigInt('0x' + fix.salt);
const x = await c.generatePasswordHash(saltBig, fix.handle, fix.password);
const v = await c.generateVerifier(x);
const expectedV = BigInt('0x' + fix.verifier);
assert.equal(v, expectedV, `verifier mismatch:\n  TS: ${v.toString(16)}\n  PY: ${fix.verifier}`);

// 2. End-to-end: with pinned client-secret a, check that respondLogin
//    produces the same M1 the fixture recorded.
const a = BigInt('0x' + fix.client_a_priv);
const A = await c.generatePublic(a);
// Sanity: padded to 384, equals fix.ke1_A.
const Apadded = A.toString(16).padStart(384 * 2, '0');
assert.equal(Apadded, fix.ke1_A, 'A doesn\'t match fixture');

// Build a fake SrpClientLogin state with our pinned a, then run respondLogin.
const state = { identity: fix.handle, password: fix.password, secret: a, ke1: fromHex(fix.ke1_A) };
const m1 = await respondLogin(state, fromHex(fix.server_response));
assert.equal(toHex(m1), fix.expected_M1.match(/.{2}/g).join(''),
  `M1 mismatch:\n  TS: ${toHex(m1)}\n  PY: ${fix.expected_M1}`);

// 3. verifyServer accepts the matching M2.
verifyServer(state, fromHex(fix.expected_M2));

// 4. verifyServer rejects an altered M2.
const badM2 = fromHex(fix.expected_M2);
badM2[0] = badM2[0] ^ 0xff;
assert.throws(() => verifyServer(state, badM2), /server proof mismatch/);

console.log('srp.test: ok');
